# Movie Recommender System Using SVD 

This is an implementation of the example discussed under 11.3 in http://infolab.stanford.edu/~ullman/mmds/book.pdf


In [2]:
import csv
import numpy as np
dataset=list()
fp=open('dataset.txt','r')
reader = csv.reader(fp, delimiter=',')
for row in reader:
    print(row)
    dataset.append(row)


['X', ' Matrix', ' Alien', ' Star_wars', ' Csablanca', ' Titanic']
['Joe', ' 1', '1', '1', '0', '0']
['jim', ' 3', '3', '3', '0', '0']
['john', '4', '4', '4', '0', '0']
['jack', '5', '5', '5', '0', '0']
['jill', ' 0', '0', '0', '4', '4']
['jenny', ' 0', '0', '0', '5', '5']
['jane', ' 0', '0', '0', '2', '2']


In [3]:
#Convert the dataset into suitable form
movies=list()
users=list()
for i in dataset[0]:
    movies.append(i)
for i in dataset:
    users.append(i[0])
movies.remove("X")
users.remove("X")
dataset.pop(0)          #Removing movie_names
for i in dataset:       #Removing user_names
    i.pop(0)       
m=list(dataset)
M=np.mat(m,dtype=int)
print(M)

[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 0 0 4 4]
 [0 0 0 5 5]
 [0 0 0 2 2]]


In [4]:
def SVD(M,dim):
    Mt=np.transpose(M)
    
    #To Calculate U
    prd=np.dot(M,Mt)
    
    #Eigen Value Decomposition
    eigenvalue,eigenvec=np.linalg.eig(prd)
    
    #Indirect sort on eigenvalue to find out the proper indices, the same can 
    #be used with corresponding eigenvectors
    sortindex=eigenvalue.argsort()[::-1]
     
    #Sort Eigen values
    eigenvalue=eigenvalue[sortindex]    
    
    #Sort and reduce U to nXdim
    U=eigenvec[:,sortindex]
    U=U[:,0:dim]
    U=np.real(U)
    U=np.around(U,decimals=2)
  
     #To calculate sigma
    sigma=np.sqrt(abs(eigenvalue))
    
    energy_den=np.sum(np.square(sigma))
    sigma=sigma[0:dim]
    energy_num=np.sum(np.square(sigma))
    sigma=np.around(sigma,decimals=2)
    
    print("Energy= ",energy_num/energy_den)
    
    
    #To Calculate V
    prd=np.dot(Mt,M)
    eigenvalue,eigenvec=np.linalg.eig(prd)
    sortindex=eigenvalue.argsort()[::-1]
    V=eigenvec[:,sortindex]
    V=V[:,0:dim]
    V=np.real(V)
    V=np.around(V,decimals=2) 
    
    
    return U,sigma,V
 

In [5]:
#TO ILLUSTRATE WORKING OF Argsort
x = np.array([3, 1, 2])
print(x)
indices=np.argsort(x)
print('Sorted indices:', indices)
x=x[indices]
print(x)

[3 1 2]
Sorted indices: [1 2 0]
[1 2 3]


In [6]:
U,sigma,V=SVD(M,2)


print("U ", U)
print("---------------------------------------")
print("sigma ", sigma)
print("---------------------------------------")
print("Vt ", V.transpose())
print("---------------------------------------")


Energy=  1.0
U  [[-0.14  0.  ]
 [-0.42  0.  ]
 [-0.56  0.  ]
 [-0.7   0.  ]
 [ 0.    0.6 ]
 [ 0.    0.75]
 [ 0.    0.3 ]]
---------------------------------------
sigma  [ 12.37   9.49]
---------------------------------------
Vt  [[ 0.58  0.58  0.58  0.    0.  ]
 [ 0.    0.    0.    0.71  0.71]]
---------------------------------------


**Expected Output:**

**Energy**=  1.0

**U** = [[-0.14  0.  ]
 [-0.42  0.  ]
 [-0.56  0.  ]
 [-0.7   0.  ]
 [ 0.    0.6 ]
 [ 0.    0.75]
 [ 0.    0.3 ]]

**sigma** = [ 12.37   9.49]

**Vt** =  [[ 0.58  0.58  0.58  0.    0.  ]
 [ 0.    0.    0.    0.71  0.71]]


In [7]:
sigma=np.diag(sigma)
M_SVD=np.dot(np.dot(U,sigma),V.transpose())

In [8]:
np.abs(M_SVD)

array([[ 1.004444,  1.004444,  1.004444,  0.      ,  0.      ],
       [ 3.013332,  3.013332,  3.013332,  0.      ,  0.      ],
       [ 4.017776,  4.017776,  4.017776,  0.      ,  0.      ],
       [ 5.02222 ,  5.02222 ,  5.02222 ,  0.      ,  0.      ],
       [ 0.      ,  0.      ,  0.      ,  4.04274 ,  4.04274 ],
       [ 0.      ,  0.      ,  0.      ,  5.053425,  5.053425],
       [ 0.      ,  0.      ,  0.      ,  2.02137 ,  2.02137 ]])

In [9]:
M

matrix([[1, 1, 1, 0, 0],
        [3, 3, 3, 0, 0],
        [4, 4, 4, 0, 0],
        [5, 5, 5, 0, 0],
        [0, 0, 0, 4, 4],
        [0, 0, 0, 5, 5],
        [0, 0, 0, 2, 2]])

In [10]:
def query(q,V):
    prd=np.dot(q,V)
    Vt=np.transpose(V)
    print(abs(prd))
    other=np.dot(prd,Vt)
    print(abs(other))
    return

In [11]:
query([4,0,0,0,0],V)

[ 2.32  0.  ]
[ 1.3456  1.3456  1.3456  0.      0.    ]
