1.Introduction
-created by Guido Van Rossum and first released in 1991.
-versions (2.7 and 3.6) 
-interpreted Language
-free and open Source(https://www.python.org/)
-object-oriented language & large standard libraries
-integrated (C, C++, JAVA etc)

In [1]:
import sys 
sys.version

'3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]'

In [2]:
a=-12
b=985.230
c="Good evening!!!!"
d=[2,'what',{2,3}]
e={'date':'04-Mar-2018','time':'17:50'}
f=(-34,-43,'4')
g={2,'l',7*2}
h=True   #or False

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'dict'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [3]:
print("Hello world!!!")
print(b)
print(23+34)
print(b*23)
print('Hello '*3)
print(str(a)+' is an integer')
print(type(a))
#this line is commented

Hello world!!!
985.23
57
22660.29
Hello Hello Hello 
-12 is an integer
<class 'int'>


In [4]:
number=input('Enter any number')
number

Enter any number75474


'75474'

In [5]:
#colon & indentation instead of { }
Num=10
if(Num>0):
    print("Num is positive")
elif(Num==0):
    print("Num is zero")
else:
    print("Num is negative")

Num is positive


In [6]:
#single line if-else
#usage:result = value_true if condition else value_false
result = "even" if Num % 2 == 0 else "odd"
result

'even'

In [7]:
Num=7
while(Num>0):
    print(Num)
    Num-=1

7
6
5
4
3
2
1


In [8]:
#initialization and incrementions are implicit
for i in range(6):
    print(i)

0
1
2
3
4
5


In [9]:
#initialized to 2, till 9(not included) with hops=3)
# similar to for(i=2;i<9,i+=3)
for i in range(2,9,3):
    print(i)

2
5
8


In [10]:
def sumfun(a,b):
    c=a+b
    return c

sumfun(91.5,4)

95.5

In [11]:
a=[1,2.0,'c','$',5,6]
print(a[2])
print(a[-2])      #from last

#list slicing
print(a[2:4])     #from index=2 to 4(excluding 4)
print(a[:3])      #from starting to 3
print(a[4:])      #from index=4 till last
print(a[1:5:2])   #from index=1 to 5 with hops=2. i,e index=1,3
print(a[::2])     #from first to last with hops=2

c
5
['c', '$']
[1, 2.0, 'c']
[5, 6]
[2.0, '$']
[1, 'c', 5]


In [12]:
b=(2,4,67,78,'z')
print(b[-3])
#similar to lists

67


In [13]:
x={'seven':7,'six':6,'two':2}
print(x['two'])

y={'college':'SJCE','place':'Mysore','date':'04-March-2018'}
print(y['place'])

print(y.items())
print(y.keys())
print(y.values())

2
Mysore
dict_items([('college', 'SJCE'), ('place', 'Mysore'), ('date', '04-March-2018')])
dict_keys(['college', 'place', 'date'])
dict_values(['SJCE', 'Mysore', '04-March-2018'])


In [14]:
import numpy as np
print(np.__version__)

1.13.3


In [15]:
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [16]:
b = np.arange(15).reshape(3, 5)
print(b)
print(b.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [17]:
c = np.zeros((4,2)) 
print(c)
d= np.ones((2,4))
d

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
e= np.full((2,2), 7)
e

array([[7, 7],
       [7, 7]])

In [19]:
f=np.random.random((4,3)) 
f

array([[ 0.68783796,  0.23570794,  0.6117438 ],
       [ 0.75969875,  0.51395907,  0.93167508],
       [ 0.59465034,  0.31355868,  0.44092869],
       [ 0.34321301,  0.05659171,  0.24131815]])

In [20]:
a=np.array([1,2,3])
b=np.array([2,3,4])
print(a*b)
print(a+b)

[ 2  6 12]
[3 5 7]


In [21]:
(a*b).sum()

20

In [22]:
print(a.dot(b))
print(np.dot(a,b))

20
20


In [23]:
ar = np.arange(10)
ar.reshape(2, -1)     # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a = np.arange(10).reshape(2,-1)   
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
ar = np.arange(10)
out = np.where(ar % 2 == 1, -1, ar)
print(ar)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [26]:
M=np.array([[1,2],[3,4]])
print(M)
print(M[0])
print(M[0][1])

[[1 2]
 [3 4]]
[1 2]
2


In [27]:
M.T  #transpose of matrix M

array([[1, 3],
       [2, 4]])

In [28]:
np.diag(M)

array([1, 4])

In [29]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
print(M.max())
print(M.min())
print(M.sum())
print(M.mean())
print(np.median(M))
np.var(M)

4
1
10
2.5
2.5


1.25

In [31]:
i=np.linalg.inv(M)
print(i)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
M.dot(i)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [33]:
import pandas as pd

In [34]:
X=pd.read_csv('Iris.csv')
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0    1            5.1           3.5            1.4           0.2   
1    2            4.9           3.0            1.4           0.2   
2    3            4.7           3.2            1.3           0.2   
3    4            4.6           3.1            1.5           0.2   
4    5            5.0           3.6            1.4           0.2   
5    6            5.4           3.9            1.7           0.4   
6    7            4.6           3.4            1.4           0.3   
7    8            5.0           3.4            1.5           0.2   
8    9            4.4           2.9            1.4           0.2   
9   10            4.9           3.1            1.5           0.1   
10  11            7.0           3.2            4.7           1.4   
11  12            6.4           3.2            4.5           1.5   
12  13            6.9           3.1            4.9           1.5   
13  14            5.5           2.3            4.0           1.3   
14  15            6.5           2.8            4.6           1.5   
15  16            5.7           2.8            4.5           1.3   
16  17            6.3           3.3            4.7           1.6   
17  18            4.9           2.4            3.3           1.0   
18  19            6.6           2.9            4.6           1.3   
19  20            5.2           2.7            3.9           1.4   
20  21            6.3           3.3            6.0           2.5   
21  22            5.8           2.7            5.1           1.9   
22  23            7.1           3.0            5.9           2.1   
23  24            6.3           2.9            5.6           1.8   
24  25            6.5           3.0            5.8           2.2   
25  26            7.6           3.0            6.6           2.1   
26  27            4.9           2.5            4.5           1.7   
27  28            7.3           2.9            6.3           1.8   
28  29            6.7           2.5            5.8           1.8   
29  30            7.2           3.6            6.1           2.5   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
6       Iris-setosa  
7       Iris-setosa  
8       Iris-setosa  
9       Iris-setosa  
10  Iris-versicolor  
11  Iris-versicolor  
12  Iris-versicolor  
13  Iris-versicolor  
14  Iris-versicolor  
15  Iris-versicolor  
16  Iris-versicolor  
17  Iris-versicolor  
18  Iris-versicolor  
19  Iris-versicolor  
20   Iris-virginica  
21   Iris-virginica  
22   Iris-virginica  
23   Iris-virginica  
24   Iris-virginica  
25   Iris-virginica  
26   Iris-virginica  
27   Iris-virginica  
28   Iris-virginica  
29   Iris-virginica

In [35]:
type(X)

pandas.core.frame.DataFrame

In [36]:
X.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [37]:
X.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
25  26            7.6           3.0            6.6           2.1   
26  27            4.9           2.5            4.5           1.7   
27  28            7.3           2.9            6.3           1.8   
28  29            6.7           2.5            5.8           1.8   
29  30            7.2           3.6            6.1           2.5   

           Species  
25  Iris-virginica  
26  Iris-virginica  
27  Iris-virginica  
28  Iris-virginica  
29  Iris-virginica

In [38]:
X.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [39]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
Id               30 non-null int64
SepalLengthCm    30 non-null float64
SepalWidthCm     30 non-null float64
PetalLengthCm    30 non-null float64
PetalWidthCm     30 non-null float64
Species          30 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 1.5+ KB


In [40]:
X.count()

Id               30
SepalLengthCm    30
SepalWidthCm     30
PetalLengthCm    30
PetalWidthCm     30
Species          30
dtype: int64

In [41]:
X.shape

(30, 6)

In [42]:
X['SepalLengthCm']   #extracting column 'SepalLengthCm'

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    7.0
11    6.4
12    6.9
13    5.5
14    6.5
15    5.7
16    6.3
17    4.9
18    6.6
19    5.2
20    6.3
21    5.8
22    7.1
23    6.3
24    6.5
25    7.6
26    4.9
27    7.3
28    6.7
29    7.2
Name: SepalLengthCm, dtype: float64

In [43]:
type(X['SepalLengthCm'])   

pandas.core.series.Series

In [44]:
X.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  30.000000      30.000000     30.000000      30.000000     30.000000
mean   15.500000       5.843333      3.040000       3.863333      1.213333
std     8.803408       0.964073      0.372873       1.881394      0.789034
min     1.000000       4.400000      2.300000       1.300000      0.100000
25%     8.250000       4.925000      2.825000       1.500000      0.225000
50%    15.500000       5.750000      3.000000       4.500000      1.400000
75%    22.750000       6.575000      3.275000       5.475000      1.800000
max    30.000000       7.600000      3.900000       6.600000      2.500000

In [45]:
X.iloc[0]   #first row

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

In [46]:
type(X.iloc[0])

pandas.core.series.Series

In [47]:
X.iloc[0][2]

3.5

In [48]:
type(X.iloc[0][2])

numpy.float64

In [49]:
X[2:5]['SepalWidthCm']

2    3.2
3    3.1
4    3.6
Name: SepalWidthCm, dtype: float64

In [50]:
X.cov()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             77.500000       5.650000     -1.441379      14.805172   
SepalLengthCm   5.650000       0.929437     -0.006621       1.589920   
SepalWidthCm   -1.441379      -0.006621      0.139034      -0.237448   
PetalLengthCm  14.805172       1.589920     -0.237448       3.539644   
PetalWidthCm    6.168966       0.613195     -0.085034       1.446713   

               PetalWidthCm  
Id                 6.168966  
SepalLengthCm      0.613195  
SepalWidthCm      -0.085034  
PetalLengthCm      1.446713  
PetalWidthCm       0.622575

In [51]:
X.corr()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.665714     -0.439103       0.893887   
SepalLengthCm  0.665714       1.000000     -0.018418       0.876568   
SepalWidthCm  -0.439103      -0.018418      1.000000      -0.338476   
PetalLengthCm  0.893887       0.876568     -0.338476       1.000000   
PetalWidthCm   0.888108       0.806108     -0.289027       0.974556   

               PetalWidthCm  
Id                 0.888108  
SepalLengthCm      0.806108  
SepalWidthCm      -0.289027  
PetalLengthCm      0.974556  
PetalWidthCm       1.000000

In [52]:
Z=np.array([[1,2,3],[4,5,6],[7,8,9]])
Z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#To create Series(1D)
M=pd.Series(Z[1])
M

0    4
1    5
2    6
dtype: int32

In [54]:
#To create DataFrame(2D)
N=pd.DataFrame(Z)
N

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9